workspace = {members = ["hello", "bye"]}
[package]
name = "latihan"
version = "0.3.0"
edition = "2024"

[dependencies]
latihan-pelajaran-bahasa-pemograman-rust-pzn-say-hello = { version = "0.6.0", features = ["all"] }
hello = { path = "hello" }
bye = { path = "bye" }

[features]
say_hello = []
say_goodbye = []
all = ["say_hello", "say_goodbye"]
default = []

[dev-dependencies]
uuid = { version = "=1.8.0", features = ["v4"] }
